"""Tests for native-table detection and editable OOXML emission.

End-to-end fixture-driven tests. The flattened-table fixture
``tests/fixtures/visual_table.ppt`` is generated by
``scripts/make_table_fixture.py`` (requires PowerPoint COM). When the
fixture is absent the tests skip, so unit-test runs without COM still
work and COM-enabled runs gain regression coverage.
"""
from __future__ import annotations

import tempfile
import unittest
import zipfile
from pathlib import Path

from ppt2pptx import convert
from ppt2pptx.cfb import CompoundFile
from ppt2pptx.ppt import (
    Presentation,
    Slide,
    Table,
    TableCell,
    extract_presentation,
)

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_TABLE = ROOT / "tests" / "fixtures" / "visual_table.ppt"


class ConvertEmitsEditableTableTests(unittest.TestCase):
    """Converting the flattened-table fixture yields a PPTX with a real
    <a:tbl> graphicFrame; the flattened cells are not re-emitted as
    scattered shapes/text-boxes."""

    @classmethod
    def setUpClass(cls):
        if not FIXTURE_TABLE.exists():
            raise unittest.SkipTest(
                f"fixture {FIXTURE_TABLE} not generated (requires PowerPoint COM)"
            )
        cls.tmpdir = Path(tempfile.mkdtemp(prefix="ppt2pptx-table-test-"))
        cls.out_path = cls.tmpdir / "out.pptx"
        cfb = CompoundFile(FIXTURE_TABLE.read_bytes())
        stream = cfb.open_stream("PowerPoint Document")
        cls.pres = extract_presentation(stream)
        convert(str(FIXTURE_TABLE), str(cls.out_path))
        with zipfile.ZipFile(cls.out_path) as z:
            cls.slide_xml = z.read("ppt/slides/slide1.xml").decode("utf-8")

    def test_out_pptx_exists(self):
        self.assertTrue(self.out_path.exists())

    def test_slide_has_editable_a_tbl(self):
        self.assertIn(
            "<a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/table\">",
            self.slide_xml,
        )
        self.assertIn("<a:tbl>", self.slide_xml)
        self.assertIn("<a:tableStyleId>", self.slide_xml)
        self.assertIn("<a:tblBorders>", self.slide_xml)

    def test_grid_is_3x3(self):
        # The fixture uses AddTable(3,3,...) so a 3x3 grid is expected.
        self.assertEqual(self.slide_xml.count("<a:gridCol"), 3)
        self.assertEqual(self.slide_xml.count("<a:tr"), 3)
        self.assertEqual(self.slide_xml.count("<a:tc>"), 9)

    def test_borders_default_to_one_point(self):
        # _table_frames emits 1pt (12700 EMU) borders, matching PowerPoint's
        # native table default.
        self.assertIn('w="12700"', self.slide_xml)

    def test_presentation_carries_detected_table(self):
        self.assertIsInstance(self.pres, Presentation)
        self.assertGreaterEqual(len(self.pres.slides), 1)
        slide = self.pres.slides[0]
        self.assertIsInstance(slide, Slide)
        self.assertGreater(len(slide.tables), 0)
        table = slide.tables[0]
        self.assertIsInstance(table, Table)
        self.assertEqual(table.rows, 3)
        self.assertEqual(table.cols, 3)
        self.assertEqual(len(table.cells), 9)
        for cell in table.cells:
            self.assertIsInstance(cell, TableCell)
            self.assertTrue(cell.text)

    def test_excluded_offsets_cover_cells_and_borders(self):
        # The presentation tracks offsets that were absorbed into tables so
        # downstream code (freeform warning, shape iteration) can skip them.
        self.assertGreater(len(self.pres.excluded_offsets), 0)
        # Each cell + each border line should be excluded. 3x3 cells + at
        # least 4 interior gridlines = >= 13.
        self.assertGreaterEqual(len(self.pres.excluded_offsets), 12)

    def test_flattened_cells_not_re_emitted(self):
        # Before the table fix the fixture produced 10 text boxes and 8
        # basic shapes (cells + border lines). With the editable table the
        # converter must collapse the cells into a single <a:tbl>, leaving
        # only the pre-existing chrome shapes (the master dividers).
        text_box_count = self.slide_xml.count("<p:sp>") - self.slide_xml.count(
            "<a:graphicData"
        )
        # We allow a small number of non-table shapes (e.g. master dividers)
        # but assert the converter no longer emits one textbox per cell.
        # Each flattened cell would add a <p:sp><p:nvSpPr>...<a:t>...</a:t>.
        cell_text_markers = sum(
            self.slide_xml.count(f">R{r}C{c}<") for r in range(1, 4) for c in range(1, 4)
        )
        # All 9 cell labels should appear (now inside <a:tbl> cells, not
        # separate textboxes). The count is at most 9 (one per cell).
        self.assertEqual(cell_text_markers, 9)


if __name__ == "__main__":
    unittest.main()